spring.application.name=MemberManagementAssignment
spring.datasource.url=jdbc:postgresql://localhost:5432/surest
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate

# Flyway will manage schema, not Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true